version: '3.9'

services:
  postgres2:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "userservice"
      POSTGRES_USER: "alexeykiselev"
      POSTGRES_PASSWORD: "kisliy"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /Users/alexeykiselev/Docker/UserService/init-script:/docker-entrypoint-initdb.d
      - /opt/homebrew/var/postgresql@16:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alexeykiselev -d userservice"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  userservice-data: